-- Auto-generated from data/gifts.ts — run after schema.sql
-- IDs are generated by Supabase (gen_random_uuid).
insert into public.gifts (name, price, image, category, available, description, purchase_link)
values
  ('Jogo de Panelas Ceramic Premium', 899.90, 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80', 'Cozinha', true, '', ''),
  ('Cafeteira Espresso Nespresso Vertuo', 799.00, 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=600&q=80', 'Cozinha', true, '', ''),
  ('Liquidificador Vitamix Pro-Series', 459.90, 'https://images.unsplash.com/photo-1578643463396-0997cb5328c1?auto=format&fit=crop&w=600&q=80', 'Cozinha', true, '', ''),
  ('Jogo de Pratos de Cerâmica Artesanal', 349.90, 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=600&q=80', 'Cozinha', true, '', ''),
  ('Batedeira Planetária KitchenAid Artisan', 2499.00, 'https://images.unsplash.com/photo-1594385208974-2e75f9d8a8f6?auto=format&fit=crop&w=600&q=80', 'Cozinha', true, '', ''),
  ('Jogo de Toalhas de Algodão Egípcio (5 peças)', 299.90, 'https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=600&q=80', 'Banheiro', true, '', ''),
  ('Kit Organizador de Banheiro em Bambu', 149.90, 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=600&q=80', 'Banheiro', true, '', ''),
  ('Espelho Inteligente com LED e Touch Screen', 549.00, 'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=600&q=80', 'Banheiro', true, '', ''),
  ('Difusor Aromático Ultrassônico de Cerâmica', 189.90, 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=600&q=80', 'Banheiro', true, '', ''),
  ('Roupão de Banho de Microfibra Premium', 220.00, 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=600&q=80', 'Banheiro', true, '', ''),
  ('Luminária de Chão Minimalista Nordic', 389.90, 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=600&q=80', 'Sala de Estar', true, '', ''),
  ('Par de Almofadas Premium em Linho Cru', 129.90, 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e6?auto=format&fit=crop&w=600&q=80', 'Sala de Estar', true, '', ''),
  ('Mesa de Apoio Lateral em Madeira Maciça', 420.00, 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&w=600&q=80', 'Sala de Estar', true, '', ''),
  ('Vaso de Cerâmica Off-White com Planta Seca', 99.90, 'https://images.unsplash.com/photo-1512428559087-560fa5ceab42?auto=format&fit=crop&w=600&q=80', 'Sala de Estar', true, '', ''),
  ('Tapete Geométrico Premium Soft (2.0x1.5m)', 649.90, 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=600&q=80', 'Sala de Estar', true, '', ''),
  ('Jogo de Cama de Cetim de Algodão 400 Fios', 499.90, 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=600&q=80', 'Quarto', true, '', ''),
  ('Par de Travesseiros Viscoelásticos Nasa Duoflex', 189.90, 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e6?auto=format&fit=crop&w=600&q=80&q=80', 'Quarto', true, '', ''),
  ('Manta Aconchegante de Tricô Artesanal', 179.90, 'https://images.unsplash.com/photo-1543294001-f7cbfe92237e?auto=format&fit=crop&w=600&q=80', 'Quarto', true, '', ''),
  ('Kit Cabides de Veludo Preto (30 unidades)', 89.90, 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=600&q=80', 'Quarto', true, '', ''),
  ('Luminária de Cabeceira com Indução Smart', 249.90, 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=600&q=80', 'Quarto', true, '', ''),
  ('Caixa de Som Inteligente Echo Show 8 Alexa', 899.00, 'https://images.unsplash.com/photo-1546054454-aa26e2b734c7?auto=format&fit=crop&w=600&q=80', 'Presentes Especiais', true, '', ''),
  ('Adega de Vinhos Climatizada (12 Garrafas)', 1299.90, 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80', 'Presentes Especiais', true, '', ''),
  ('Robô Aspirador Mapeamento Inteligente Eufy', 1599.00, 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=600&q=80', 'Presentes Especiais', true, '', ''),
  ('Fritadeira Elétrica Airfryer Philips Walita', 679.90, 'https://images.unsplash.com/photo-1621972750749-0fbb1abb7736?auto=format&fit=crop&w=600&q=80', 'Presentes Especiais', true, '', ''),
  ('Fechadura Digital Inteligente Yale Smart', 949.00, 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=600&q=80', 'Presentes Especiais', true, '', '');
