import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const source = fs.readFileSync(
  path.join(__dirname, '../data/gifts.ts'),
  'utf8'
);

const blocks = source.match(/\{[^}]+\}/gs) ?? [];
const rows = [];

for (const block of blocks) {
  const name = block.match(/name:\s*'([^']+)'/)?.[1];
  const price = block.match(/price:\s*([\d.]+)/)?.[1];
  const image = block.match(/image:\s*'([^']+)'/)?.[1];
  const category = block.match(/category:\s*'([^']+)'/)?.[1];
  if (!name || !price || !image || !category) continue;

  const esc = (s) => s.replace(/'/g, "''");
  rows.push(
    `  ('${esc(name)}', ${price}, '${esc(image)}', '${esc(category)}', true, '', '')`
  );
}

const sql = `-- Auto-generated from data/gifts.ts — run after schema.sql
-- IDs are generated by Supabase (gen_random_uuid).
insert into public.gifts (name, price, image, category, available, description, purchase_link)
values
${rows.join(',\n')};
`;

fs.writeFileSync(path.join(__dirname, '../supabase/seed.sql'), sql);
console.log(`Wrote ${rows.length} gifts to supabase/seed.sql`);
